// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Banks                   string
	CryptoAssetsHistory     string
	CryptoAssetsTotal       string
	CurrentMonthBalance     string
	CurrentMonthIncome      string
	DefaultExpensesCategory string
	DefaultIncomeCategory   string
	Goals                   string
	GooseMigrations         string
	TotalWealth             string
	Transactions            string
	UserBanks               string
	UserExpensesCategory    string
	UserIncomeCategory      string
	Users                   string
}{
	Banks:                   "banks",
	CryptoAssetsHistory:     "crypto_assets_history",
	CryptoAssetsTotal:       "crypto_assets_total",
	CurrentMonthBalance:     "current_month_balance",
	CurrentMonthIncome:      "current_month_income",
	DefaultExpensesCategory: "default_expenses_category",
	DefaultIncomeCategory:   "default_income_category",
	Goals:                   "goals",
	GooseMigrations:         "goose_migrations",
	TotalWealth:             "total_wealth",
	Transactions:            "transactions",
	UserBanks:               "user_banks",
	UserExpensesCategory:    "user_expenses_category",
	UserIncomeCategory:      "user_income_category",
	Users:                   "users",
}
