// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCurrentMonthBills(t *testing.T) {
	t.Parallel()

	query := CurrentMonthBills()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCurrentMonthBillsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCurrentMonthBillsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CurrentMonthBills().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCurrentMonthBillsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CurrentMonthBillSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCurrentMonthBillsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CurrentMonthBillExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if CurrentMonthBill exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CurrentMonthBillExists to return true, but got false.")
	}
}

func testCurrentMonthBillsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	currentMonthBillFound, err := FindCurrentMonthBill(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if currentMonthBillFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCurrentMonthBillsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CurrentMonthBills().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCurrentMonthBillsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CurrentMonthBills().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCurrentMonthBillsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	currentMonthBillOne := &CurrentMonthBill{}
	currentMonthBillTwo := &CurrentMonthBill{}
	if err = randomize.Struct(seed, currentMonthBillOne, currentMonthBillDBTypes, false, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}
	if err = randomize.Struct(seed, currentMonthBillTwo, currentMonthBillDBTypes, false, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = currentMonthBillOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = currentMonthBillTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CurrentMonthBills().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCurrentMonthBillsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	currentMonthBillOne := &CurrentMonthBill{}
	currentMonthBillTwo := &CurrentMonthBill{}
	if err = randomize.Struct(seed, currentMonthBillOne, currentMonthBillDBTypes, false, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}
	if err = randomize.Struct(seed, currentMonthBillTwo, currentMonthBillDBTypes, false, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = currentMonthBillOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = currentMonthBillTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func currentMonthBillBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func currentMonthBillAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CurrentMonthBill) error {
	*o = CurrentMonthBill{}
	return nil
}

func testCurrentMonthBillsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CurrentMonthBill{}
	o := &CurrentMonthBill{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill object: %s", err)
	}

	AddCurrentMonthBillHook(boil.BeforeInsertHook, currentMonthBillBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	currentMonthBillBeforeInsertHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.AfterInsertHook, currentMonthBillAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	currentMonthBillAfterInsertHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.AfterSelectHook, currentMonthBillAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	currentMonthBillAfterSelectHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.BeforeUpdateHook, currentMonthBillBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	currentMonthBillBeforeUpdateHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.AfterUpdateHook, currentMonthBillAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	currentMonthBillAfterUpdateHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.BeforeDeleteHook, currentMonthBillBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	currentMonthBillBeforeDeleteHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.AfterDeleteHook, currentMonthBillAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	currentMonthBillAfterDeleteHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.BeforeUpsertHook, currentMonthBillBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	currentMonthBillBeforeUpsertHooks = []CurrentMonthBillHook{}

	AddCurrentMonthBillHook(boil.AfterUpsertHook, currentMonthBillAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	currentMonthBillAfterUpsertHooks = []CurrentMonthBillHook{}
}

func testCurrentMonthBillsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCurrentMonthBillsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(currentMonthBillColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCurrentMonthBillToOneUserBankUsingBankUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CurrentMonthBill
	var foreign UserBank

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, currentMonthBillDBTypes, false, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userBankDBTypes, false, userBankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserBank struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.BankUserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.BankUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserBankHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *UserBank) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := CurrentMonthBillSlice{&local}
	if err = local.L.LoadBankUser(ctx, tx, false, (*[]*CurrentMonthBill)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.BankUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.BankUser = nil
	if err = local.L.LoadBankUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.BankUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testCurrentMonthBillToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CurrentMonthBill
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, currentMonthBillDBTypes, false, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := CurrentMonthBillSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*CurrentMonthBill)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testCurrentMonthBillToOneSetOpUserBankUsingBankUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CurrentMonthBill
	var b, c UserBank

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, currentMonthBillDBTypes, false, strmangle.SetComplement(currentMonthBillPrimaryKeyColumns, currentMonthBillColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userBankDBTypes, false, strmangle.SetComplement(userBankPrimaryKeyColumns, userBankColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userBankDBTypes, false, strmangle.SetComplement(userBankPrimaryKeyColumns, userBankColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*UserBank{&b, &c} {
		err = a.SetBankUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.BankUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.BankUserCurrentMonthBills[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.BankUserID != x.ID {
			t.Error("foreign key was wrong value", a.BankUserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.BankUserID))
		reflect.Indirect(reflect.ValueOf(&a.BankUserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.BankUserID != x.ID {
			t.Error("foreign key was wrong value", a.BankUserID, x.ID)
		}
	}
}
func testCurrentMonthBillToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CurrentMonthBill
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, currentMonthBillDBTypes, false, strmangle.SetComplement(currentMonthBillPrimaryKeyColumns, currentMonthBillColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CurrentMonthBills[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testCurrentMonthBillsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCurrentMonthBillsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CurrentMonthBillSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCurrentMonthBillsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CurrentMonthBills().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	currentMonthBillDBTypes = map[string]string{`ID`: `uuid`, `BankUserID`: `uuid`, `UserID`: `uuid`, `Amount`: `numeric`, `PeriodMonth`: `date`, `IsPayed`: `boolean`, `Name`: `character varying`}
	_                       = bytes.MinRead
)

func testCurrentMonthBillsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(currentMonthBillPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(currentMonthBillAllColumns) == len(currentMonthBillPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCurrentMonthBillsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(currentMonthBillAllColumns) == len(currentMonthBillPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CurrentMonthBill{}
	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, currentMonthBillDBTypes, true, currentMonthBillPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(currentMonthBillAllColumns, currentMonthBillPrimaryKeyColumns) {
		fields = currentMonthBillAllColumns
	} else {
		fields = strmangle.SetComplement(
			currentMonthBillAllColumns,
			currentMonthBillPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CurrentMonthBillSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCurrentMonthBillsUpsert(t *testing.T) {
	t.Parallel()

	if len(currentMonthBillAllColumns) == len(currentMonthBillPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CurrentMonthBill{}
	if err = randomize.Struct(seed, &o, currentMonthBillDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CurrentMonthBill: %s", err)
	}

	count, err := CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, currentMonthBillDBTypes, false, currentMonthBillPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CurrentMonthBill struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CurrentMonthBill: %s", err)
	}

	count, err = CurrentMonthBills().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
