// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDefaultExpensesCategories(t *testing.T) {
	t.Parallel()

	query := DefaultExpensesCategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDefaultExpensesCategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDefaultExpensesCategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DefaultExpensesCategories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDefaultExpensesCategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DefaultExpensesCategorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDefaultExpensesCategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DefaultExpensesCategoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DefaultExpensesCategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DefaultExpensesCategoryExists to return true, but got false.")
	}
}

func testDefaultExpensesCategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	defaultExpensesCategoryFound, err := FindDefaultExpensesCategory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if defaultExpensesCategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDefaultExpensesCategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DefaultExpensesCategories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDefaultExpensesCategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DefaultExpensesCategories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDefaultExpensesCategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	defaultExpensesCategoryOne := &DefaultExpensesCategory{}
	defaultExpensesCategoryTwo := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, defaultExpensesCategoryOne, defaultExpensesCategoryDBTypes, false, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, defaultExpensesCategoryTwo, defaultExpensesCategoryDBTypes, false, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = defaultExpensesCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = defaultExpensesCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DefaultExpensesCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDefaultExpensesCategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	defaultExpensesCategoryOne := &DefaultExpensesCategory{}
	defaultExpensesCategoryTwo := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, defaultExpensesCategoryOne, defaultExpensesCategoryDBTypes, false, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, defaultExpensesCategoryTwo, defaultExpensesCategoryDBTypes, false, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = defaultExpensesCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = defaultExpensesCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func defaultExpensesCategoryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func defaultExpensesCategoryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DefaultExpensesCategory) error {
	*o = DefaultExpensesCategory{}
	return nil
}

func testDefaultExpensesCategoriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DefaultExpensesCategory{}
	o := &DefaultExpensesCategory{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory object: %s", err)
	}

	AddDefaultExpensesCategoryHook(boil.BeforeInsertHook, defaultExpensesCategoryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryBeforeInsertHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.AfterInsertHook, defaultExpensesCategoryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryAfterInsertHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.AfterSelectHook, defaultExpensesCategoryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryAfterSelectHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.BeforeUpdateHook, defaultExpensesCategoryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryBeforeUpdateHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.AfterUpdateHook, defaultExpensesCategoryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryAfterUpdateHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.BeforeDeleteHook, defaultExpensesCategoryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryBeforeDeleteHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.AfterDeleteHook, defaultExpensesCategoryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryAfterDeleteHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.BeforeUpsertHook, defaultExpensesCategoryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryBeforeUpsertHooks = []DefaultExpensesCategoryHook{}

	AddDefaultExpensesCategoryHook(boil.AfterUpsertHook, defaultExpensesCategoryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	defaultExpensesCategoryAfterUpsertHooks = []DefaultExpensesCategoryHook{}
}

func testDefaultExpensesCategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDefaultExpensesCategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(defaultExpensesCategoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDefaultExpensesCategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDefaultExpensesCategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DefaultExpensesCategorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDefaultExpensesCategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DefaultExpensesCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	defaultExpensesCategoryDBTypes = map[string]string{`ID`: `uuid`, `Name`: `character varying`}
	_                              = bytes.MinRead
)

func testDefaultExpensesCategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(defaultExpensesCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(defaultExpensesCategoryAllColumns) == len(defaultExpensesCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDefaultExpensesCategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(defaultExpensesCategoryAllColumns) == len(defaultExpensesCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DefaultExpensesCategory{}
	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, defaultExpensesCategoryDBTypes, true, defaultExpensesCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(defaultExpensesCategoryAllColumns, defaultExpensesCategoryPrimaryKeyColumns) {
		fields = defaultExpensesCategoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			defaultExpensesCategoryAllColumns,
			defaultExpensesCategoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DefaultExpensesCategorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDefaultExpensesCategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(defaultExpensesCategoryAllColumns) == len(defaultExpensesCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DefaultExpensesCategory{}
	if err = randomize.Struct(seed, &o, defaultExpensesCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DefaultExpensesCategory: %s", err)
	}

	count, err := DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, defaultExpensesCategoryDBTypes, false, defaultExpensesCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DefaultExpensesCategory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DefaultExpensesCategory: %s", err)
	}

	count, err = DefaultExpensesCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
