// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DefaultExpensesCategory is an object representing the database table.
type DefaultExpensesCategory struct {
	ID   string `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *defaultExpensesCategoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L defaultExpensesCategoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DefaultExpensesCategoryColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var DefaultExpensesCategoryTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "default_expenses_category.id",
	Name: "default_expenses_category.name",
}

// Generated where

var DefaultExpensesCategoryWhere = struct {
	ID   whereHelperstring
	Name whereHelperstring
}{
	ID:   whereHelperstring{field: "\"default_expenses_category\".\"id\""},
	Name: whereHelperstring{field: "\"default_expenses_category\".\"name\""},
}

// DefaultExpensesCategoryRels is where relationship names are stored.
var DefaultExpensesCategoryRels = struct {
}{}

// defaultExpensesCategoryR is where relationships are stored.
type defaultExpensesCategoryR struct {
}

// NewStruct creates a new relationship struct
func (*defaultExpensesCategoryR) NewStruct() *defaultExpensesCategoryR {
	return &defaultExpensesCategoryR{}
}

// defaultExpensesCategoryL is where Load methods for each relationship are stored.
type defaultExpensesCategoryL struct{}

var (
	defaultExpensesCategoryAllColumns            = []string{"id", "name"}
	defaultExpensesCategoryColumnsWithoutDefault = []string{"name"}
	defaultExpensesCategoryColumnsWithDefault    = []string{"id"}
	defaultExpensesCategoryPrimaryKeyColumns     = []string{"id"}
	defaultExpensesCategoryGeneratedColumns      = []string{}
)

type (
	// DefaultExpensesCategorySlice is an alias for a slice of pointers to DefaultExpensesCategory.
	// This should almost always be used instead of []DefaultExpensesCategory.
	DefaultExpensesCategorySlice []*DefaultExpensesCategory
	// DefaultExpensesCategoryHook is the signature for custom DefaultExpensesCategory hook methods
	DefaultExpensesCategoryHook func(context.Context, boil.ContextExecutor, *DefaultExpensesCategory) error

	defaultExpensesCategoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	defaultExpensesCategoryType                 = reflect.TypeOf(&DefaultExpensesCategory{})
	defaultExpensesCategoryMapping              = queries.MakeStructMapping(defaultExpensesCategoryType)
	defaultExpensesCategoryPrimaryKeyMapping, _ = queries.BindMapping(defaultExpensesCategoryType, defaultExpensesCategoryMapping, defaultExpensesCategoryPrimaryKeyColumns)
	defaultExpensesCategoryInsertCacheMut       sync.RWMutex
	defaultExpensesCategoryInsertCache          = make(map[string]insertCache)
	defaultExpensesCategoryUpdateCacheMut       sync.RWMutex
	defaultExpensesCategoryUpdateCache          = make(map[string]updateCache)
	defaultExpensesCategoryUpsertCacheMut       sync.RWMutex
	defaultExpensesCategoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var defaultExpensesCategoryAfterSelectMu sync.Mutex
var defaultExpensesCategoryAfterSelectHooks []DefaultExpensesCategoryHook

var defaultExpensesCategoryBeforeInsertMu sync.Mutex
var defaultExpensesCategoryBeforeInsertHooks []DefaultExpensesCategoryHook
var defaultExpensesCategoryAfterInsertMu sync.Mutex
var defaultExpensesCategoryAfterInsertHooks []DefaultExpensesCategoryHook

var defaultExpensesCategoryBeforeUpdateMu sync.Mutex
var defaultExpensesCategoryBeforeUpdateHooks []DefaultExpensesCategoryHook
var defaultExpensesCategoryAfterUpdateMu sync.Mutex
var defaultExpensesCategoryAfterUpdateHooks []DefaultExpensesCategoryHook

var defaultExpensesCategoryBeforeDeleteMu sync.Mutex
var defaultExpensesCategoryBeforeDeleteHooks []DefaultExpensesCategoryHook
var defaultExpensesCategoryAfterDeleteMu sync.Mutex
var defaultExpensesCategoryAfterDeleteHooks []DefaultExpensesCategoryHook

var defaultExpensesCategoryBeforeUpsertMu sync.Mutex
var defaultExpensesCategoryBeforeUpsertHooks []DefaultExpensesCategoryHook
var defaultExpensesCategoryAfterUpsertMu sync.Mutex
var defaultExpensesCategoryAfterUpsertHooks []DefaultExpensesCategoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DefaultExpensesCategory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DefaultExpensesCategory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DefaultExpensesCategory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DefaultExpensesCategory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DefaultExpensesCategory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DefaultExpensesCategory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DefaultExpensesCategory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DefaultExpensesCategory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DefaultExpensesCategory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range defaultExpensesCategoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDefaultExpensesCategoryHook registers your hook function for all future operations.
func AddDefaultExpensesCategoryHook(hookPoint boil.HookPoint, defaultExpensesCategoryHook DefaultExpensesCategoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		defaultExpensesCategoryAfterSelectMu.Lock()
		defaultExpensesCategoryAfterSelectHooks = append(defaultExpensesCategoryAfterSelectHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		defaultExpensesCategoryBeforeInsertMu.Lock()
		defaultExpensesCategoryBeforeInsertHooks = append(defaultExpensesCategoryBeforeInsertHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		defaultExpensesCategoryAfterInsertMu.Lock()
		defaultExpensesCategoryAfterInsertHooks = append(defaultExpensesCategoryAfterInsertHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		defaultExpensesCategoryBeforeUpdateMu.Lock()
		defaultExpensesCategoryBeforeUpdateHooks = append(defaultExpensesCategoryBeforeUpdateHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		defaultExpensesCategoryAfterUpdateMu.Lock()
		defaultExpensesCategoryAfterUpdateHooks = append(defaultExpensesCategoryAfterUpdateHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		defaultExpensesCategoryBeforeDeleteMu.Lock()
		defaultExpensesCategoryBeforeDeleteHooks = append(defaultExpensesCategoryBeforeDeleteHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		defaultExpensesCategoryAfterDeleteMu.Lock()
		defaultExpensesCategoryAfterDeleteHooks = append(defaultExpensesCategoryAfterDeleteHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		defaultExpensesCategoryBeforeUpsertMu.Lock()
		defaultExpensesCategoryBeforeUpsertHooks = append(defaultExpensesCategoryBeforeUpsertHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		defaultExpensesCategoryAfterUpsertMu.Lock()
		defaultExpensesCategoryAfterUpsertHooks = append(defaultExpensesCategoryAfterUpsertHooks, defaultExpensesCategoryHook)
		defaultExpensesCategoryAfterUpsertMu.Unlock()
	}
}

// One returns a single defaultExpensesCategory record from the query.
func (q defaultExpensesCategoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DefaultExpensesCategory, error) {
	o := &DefaultExpensesCategory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for default_expenses_category")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DefaultExpensesCategory records from the query.
func (q defaultExpensesCategoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (DefaultExpensesCategorySlice, error) {
	var o []*DefaultExpensesCategory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DefaultExpensesCategory slice")
	}

	if len(defaultExpensesCategoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DefaultExpensesCategory records in the query.
func (q defaultExpensesCategoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count default_expenses_category rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q defaultExpensesCategoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if default_expenses_category exists")
	}

	return count > 0, nil
}

// DefaultExpensesCategories retrieves all the records using an executor.
func DefaultExpensesCategories(mods ...qm.QueryMod) defaultExpensesCategoryQuery {
	mods = append(mods, qm.From("\"default_expenses_category\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"default_expenses_category\".*"})
	}

	return defaultExpensesCategoryQuery{q}
}

// FindDefaultExpensesCategory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDefaultExpensesCategory(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*DefaultExpensesCategory, error) {
	defaultExpensesCategoryObj := &DefaultExpensesCategory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"default_expenses_category\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, defaultExpensesCategoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from default_expenses_category")
	}

	if err = defaultExpensesCategoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return defaultExpensesCategoryObj, err
	}

	return defaultExpensesCategoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DefaultExpensesCategory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no default_expenses_category provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(defaultExpensesCategoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	defaultExpensesCategoryInsertCacheMut.RLock()
	cache, cached := defaultExpensesCategoryInsertCache[key]
	defaultExpensesCategoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			defaultExpensesCategoryAllColumns,
			defaultExpensesCategoryColumnsWithDefault,
			defaultExpensesCategoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(defaultExpensesCategoryType, defaultExpensesCategoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(defaultExpensesCategoryType, defaultExpensesCategoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"default_expenses_category\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"default_expenses_category\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into default_expenses_category")
	}

	if !cached {
		defaultExpensesCategoryInsertCacheMut.Lock()
		defaultExpensesCategoryInsertCache[key] = cache
		defaultExpensesCategoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DefaultExpensesCategory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DefaultExpensesCategory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	defaultExpensesCategoryUpdateCacheMut.RLock()
	cache, cached := defaultExpensesCategoryUpdateCache[key]
	defaultExpensesCategoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			defaultExpensesCategoryAllColumns,
			defaultExpensesCategoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update default_expenses_category, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"default_expenses_category\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, defaultExpensesCategoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(defaultExpensesCategoryType, defaultExpensesCategoryMapping, append(wl, defaultExpensesCategoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update default_expenses_category row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for default_expenses_category")
	}

	if !cached {
		defaultExpensesCategoryUpdateCacheMut.Lock()
		defaultExpensesCategoryUpdateCache[key] = cache
		defaultExpensesCategoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q defaultExpensesCategoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for default_expenses_category")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for default_expenses_category")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DefaultExpensesCategorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), defaultExpensesCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"default_expenses_category\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, defaultExpensesCategoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in defaultExpensesCategory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all defaultExpensesCategory")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DefaultExpensesCategory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no default_expenses_category provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(defaultExpensesCategoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	defaultExpensesCategoryUpsertCacheMut.RLock()
	cache, cached := defaultExpensesCategoryUpsertCache[key]
	defaultExpensesCategoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			defaultExpensesCategoryAllColumns,
			defaultExpensesCategoryColumnsWithDefault,
			defaultExpensesCategoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			defaultExpensesCategoryAllColumns,
			defaultExpensesCategoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert default_expenses_category, could not build update column list")
		}

		ret := strmangle.SetComplement(defaultExpensesCategoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(defaultExpensesCategoryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert default_expenses_category, could not build conflict column list")
			}

			conflict = make([]string, len(defaultExpensesCategoryPrimaryKeyColumns))
			copy(conflict, defaultExpensesCategoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"default_expenses_category\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(defaultExpensesCategoryType, defaultExpensesCategoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(defaultExpensesCategoryType, defaultExpensesCategoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert default_expenses_category")
	}

	if !cached {
		defaultExpensesCategoryUpsertCacheMut.Lock()
		defaultExpensesCategoryUpsertCache[key] = cache
		defaultExpensesCategoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DefaultExpensesCategory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DefaultExpensesCategory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DefaultExpensesCategory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), defaultExpensesCategoryPrimaryKeyMapping)
	sql := "DELETE FROM \"default_expenses_category\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from default_expenses_category")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for default_expenses_category")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q defaultExpensesCategoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no defaultExpensesCategoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from default_expenses_category")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for default_expenses_category")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DefaultExpensesCategorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(defaultExpensesCategoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), defaultExpensesCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"default_expenses_category\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, defaultExpensesCategoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from defaultExpensesCategory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for default_expenses_category")
	}

	if len(defaultExpensesCategoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DefaultExpensesCategory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDefaultExpensesCategory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DefaultExpensesCategorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DefaultExpensesCategorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), defaultExpensesCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"default_expenses_category\".* FROM \"default_expenses_category\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, defaultExpensesCategoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DefaultExpensesCategorySlice")
	}

	*o = slice

	return nil
}

// DefaultExpensesCategoryExists checks if the DefaultExpensesCategory row exists.
func DefaultExpensesCategoryExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"default_expenses_category\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if default_expenses_category exists")
	}

	return exists, nil
}

// Exists checks if the DefaultExpensesCategory row exists.
func (o *DefaultExpensesCategory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DefaultExpensesCategoryExists(ctx, exec, o.ID)
}
